#!/bin/sh
chmod +x /etc/init.d/devgate /usr/bin/devgate*
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@devgate[-1]
	add ucitrack devgate
	set ucitrack.@devgate[-1].init=devgate
	commit ucitrack
EOF

[ -s /etc/config/devgate ] || cat > /etc/config/devgate <<'EOF'
config device
	option enable '0'
	option mac ''
	option time_from '00:00'
	option time_over '00:00'
	option week '0'
	option chain 'forward'
EOF

/etc/init.d/devgate enable >/dev/null 2>&1 || true
/etc/init.d/devgate start >/dev/null 2>&1 || true

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache /tmp/luci-*cache
/etc/init.d/rpcd reload >/dev/null 2>&1 || true
exit 0
